<?php

namespace Database\Seeders;

use App\Models\Car;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cars = [
            [
                'make' => 'Toyota',
                'model' => 'Corolla',
                'year' => 2020,
                'color' => 'Prata',
                'vin' => '1NXBR32E85Z556789',
                'license_plate' => 'ABC1234',
                'mileage' => 30000,
                'engine' => '2.0L',
                'fuel_type' => 'Gasolina',
                'transmission' => 'Automático',
                'number_of_doors' => 4,
                'body_type' => 'Sedan',
                'drivetrain' => '4x2',
                'features' => 'Ar-condicionado, Direção Hidráulica, Airbags',
                'price' => 85000.00,
                'purchase_date' => '2023-05-01',
                'purchase_price' => 75000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 1,
                'description' => 'Carro em excelente estado, com revisões em dia.',
                'location' => 'São Paulo',
            ],
            [
                'make' => 'Honda',
                'model' => 'Civic',
                'year' => 2019,
                'color' => 'Preto',
                'vin' => '2HGFB2F59CH567890',
                'license_plate' => 'DEF5678',
                'mileage' => 45000,
                'engine' => '1.8L',
                'fuel_type' => 'Gasolina',
                'transmission' => 'Manual',
                'number_of_doors' => 4,
                'body_type' => 'Sedan',
                'drivetrain' => '4x2',
                'features' => 'Ar-condicionado, Direção Elétrica, Airbags, Freios ABS',
                'price' => 80000.00,
                'purchase_date' => '2023-04-15',
                'purchase_price' => 70000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 1,
                'description' => 'Carro bem conservado, única dona, revisões anuais feitas.',
                'location' => 'Rio de Janeiro',
            ],
            [
                'make' => 'Ford',
                'model' => 'EcoSport',
                'year' => 2021,
                'color' => 'Branco',
                'vin' => '3FADP4EJ3EM123456',
                'license_plate' => 'GHI9012',
                'mileage' => 15000,
                'engine' => '1.5L',
                'fuel_type' => 'Flex',
                'transmission' => 'Automático',
                'number_of_doors' => 4,
                'body_type' => 'SUV',
                'drivetrain' => '4x2',
                'features' => 'Ar-condicionado, Direção Elétrica, Central Multimídia',
                'price' => 95000.00,
                'purchase_date' => '2023-06-10',
                'purchase_price' => 85000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 0,
                'description' => 'SUV compacto em excelente estado, bem espaçoso e econômico.',
                'location' => 'Belo Horizonte',
            ],
            [
                'make' => 'Chevrolet',
                'model' => 'Onix',
                'year' => 2022,
                'color' => 'Azul',
                'vin' => '3G1BE6SM9JS123456',
                'license_plate' => 'JKL3456',
                'mileage' => 12000,
                'engine' => '1.0L',
                'fuel_type' => 'Flex',
                'transmission' => 'Automático',
                'number_of_doors' => 4,
                'body_type' => 'Hatch',
                'drivetrain' => '4x2',
                'features' => 'Ar-condicionado, Central Multimídia, Sensor de Estacionamento',
                'price' => 70000.00,
                'purchase_date' => '2023-07-05',
                'purchase_price' => 65000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 1,
                'description' => 'Carro compacto, econômico e confortável, com baixa quilometragem.',
                'location' => 'Curitiba',
            ],
            [
                'make' => 'Volkswagen',
                'model' => 'Gol',
                'year' => 2018,
                'color' => 'Vermelho',
                'vin' => '9BWZZZ377VT000123',
                'license_plate' => 'MNO6789',
                'mileage' => 60000,
                'engine' => '1.6L',
                'fuel_type' => 'Flex',
                'transmission' => 'Manual',
                'number_of_doors' => 4,
                'body_type' => 'Hatch',
                'drivetrain' => '4x2',
                'features' => 'Ar-condicionado, Direção Hidráulica, Airbags',
                'price' => 50000.00,
                'purchase_date' => '2023-01-20',
                'purchase_price' => 45000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 2,
                'description' => 'Veículo bem conservado e com manutenções em dia.',
                'location' => 'Porto Alegre',
            ],
            [
                'make' => 'Hyundai',
                'model' => 'HB20',
                'year' => 2021,
                'color' => 'Cinza',
                'vin' => 'KMHDN45D7LU123456',
                'license_plate' => 'PQR5678',
                'mileage' => 25000,
                'engine' => '1.6L',
                'fuel_type' => 'Flex',
                'transmission' => 'Automático',
                'number_of_doors' => 4,
                'body_type' => 'Hatch',
                'drivetrain' => '4x2',
                'features' => 'Ar-condicionado, Central Multimídia, Airbags, Freios ABS',
                'price' => 80000.00,
                'purchase_date' => '2023-03-15',
                'purchase_price' => 75000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 1,
                'description' => 'Carro econômico e confortável, com central multimídia.',
                'location' => 'Brasília',
            ],
            [
                'make' => 'Nissan',
                'model' => 'Kicks',
                'year' => 2020,
                'color' => 'Preto',
                'vin' => '3N1AB7AP6GY123456',
                'license_plate' => 'STU2345',
                'mileage' => 30000,
                'engine' => '1.6L',
                'fuel_type' => 'Gasolina',
                'transmission' => 'Automático',
                'number_of_doors' => 4,
                'body_type' => 'SUV',
                'drivetrain' => '4x2',
                'features' => 'Ar-condicionado, Direção Elétrica, Freios ABS',
                'price' => 95000.00,
                'purchase_date' => '2023-02-10',
                'purchase_price' => 88000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 1,
                'description' => 'SUV espaçoso e confortável, ideal para família.',
                'location' => 'Fortaleza',
            ],
            [
                'make' => 'Renault',
                'model' => 'Duster',
                'year' => 2019,
                'color' => 'Branco',
                'vin' => '93YBB00457J123456',
                'license_plate' => 'VWX6789',
                'mileage' => 40000,
                'engine' => '2.0L',
                'fuel_type' => 'Flex',
                'transmission' => 'Manual',
                'number_of_doors' => 4,
                'body_type' => 'SUV',
                'drivetrain' => '4x2',
                'features' => 'Ar-condicionado, Direção Hidráulica, Freios ABS',
                'price' => 75000.00,
                'purchase_date' => '2023-04-12',
                'purchase_price' => 70000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 2,
                'description' => 'Veículo espaçoso e potente, ideal para aventuras.',
                'location' => 'Salvador',
            ],
            [
                'make' => 'Fiat',
                'model' => 'Argo',
                'year' => 2021,
                'color' => 'Prata',
                'vin' => '9BD17345FJ123456',
                'license_plate' => 'YZA9012',
                'mileage' => 20000,
                'engine' => '1.3L',
                'fuel_type' => 'Flex',
                'transmission' => 'Manual',
                'number_of_doors' => 4,
                'body_type' => 'Hatch',
                'drivetrain' => '4x2',
                'features' => 'Ar-condicionado, Direção Elétrica, Central Multimídia',
                'price' => 68000.00,
                'purchase_date' => '2023-06-01',
                'purchase_price' => 63000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 1,
                'description' => 'Carro compacto e moderno, com ótimo consumo.',
                'location' => 'Recife',
            ],
            [
                'make' => 'Jeep',
                'model' => 'Compass',
                'year' => 2022,
                'color' => 'Cinza',
                'vin' => '1C4NJDEB4FD123456',
                'license_plate' => 'BCD2345',
                'mileage' => 15000,
                'engine' => '2.0L',
                'fuel_type' => 'Diesel',
                'transmission' => 'Automático',
                'number_of_doors' => 4,
                'body_type' => 'SUV',
                'drivetrain' => '4x4',
                'features' => 'Ar-condicionado, Central Multimídia, Teto Solar, Freios ABS',
                'price' => 145000.00,
                'purchase_date' => '2023-08-10',
                'purchase_price' => 135000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 0,
                'description' => 'SUV robusto com tração 4x4 e teto solar panorâmico.',
                'location' => 'São Paulo',
            ],
            [
                'make' => 'BMW',
                'model' => '320i',
                'year' => 2021,
                'color' => 'Branco',
                'vin' => 'WBA8E3G58GNT12345',
                'license_plate' => 'EFG6789',
                'mileage' => 25000,
                'engine' => '2.0L',
                'fuel_type' => 'Gasolina',
                'transmission' => 'Automático',
                'number_of_doors' => 4,
                'body_type' => 'Sedan',
                'drivetrain' => '4x2',
                'features' => 'Ar-condicionado, Central Multimídia, Freios ABS, Airbags',
                'price' => 180000.00,
                'purchase_date' => '2023-02-25',
                'purchase_price' => 170000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 1,
                'description' => 'Sedan esportivo com excelente performance e conforto.',
                'location' => 'São Paulo',
            ],
            [
                'make' => 'Audi',
                'model' => 'A3',
                'year' => 2020,
                'color' => 'Preto',
                'vin' => 'WAUFFAFL1FA123456',
                'license_plate' => 'HIJ4567',
                'mileage' => 35000,
                'engine' => '1.4L',
                'fuel_type' => 'Gasolina',
                'transmission' => 'Automático',
                'number_of_doors' => 4,
                'body_type' => 'Sedan',
                'drivetrain' => '4x2',
                'features' => 'Ar-condicionado, Direção Elétrica, Central Multimídia, Airbags',
                'price' => 140000.00,
                'purchase_date' => '2023-01-30',
                'purchase_price' => 130000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 1,
                'description' => 'Sedan compacto, luxuoso e econômico.',
                'location' => 'Rio de Janeiro',
            ],
            [
                'make' => 'Mercedes-Benz',
                'model' => 'C180',
                'year' => 2019,
                'color' => 'Cinza',
                'vin' => 'WDDGF4HB1EG123456',
                'license_plate' => 'KLM8901',
                'mileage' => 40000,
                'engine' => '1.6L',
                'fuel_type' => 'Gasolina',
                'transmission' => 'Automático',
                'number_of_doors' => 4,
                'body_type' => 'Sedan',
                'drivetrain' => '4x2',
                'features' => 'Ar-condicionado, Direção Elétrica, Central Multimídia, Freios ABS',
                'price' => 160000.00,
                'purchase_date' => '2023-05-05',
                'purchase_price' => 150000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 1,
                'description' => 'Sedan premium com ótimo desempenho e conforto.',
                'location' => 'Curitiba',
            ],
            [
                'make' => 'Chevrolet',
                'model' => 'Cruze',
                'year' => 2017,
                'color' => 'Preto',
                'vin' => '1G1BE5SM8H7223456',
                'license_plate' => 'XYZ1234',
                'mileage' => 55000,
                'engine' => '1.4L',
                'fuel_type' => 'Gasolina',
                'transmission' => 'Automático',
                'number_of_doors' => 4,
                'body_type' => 'Sedan',
                'drivetrain' => '4x2',
                'features' => 'Ar-condicionado, Direção Elétrica, Freios ABS',
                'price' => 70000.00,
                'purchase_date' => '2023-07-01',
                'purchase_price' => 65000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 1,
                'description' => 'Sedan completo, com ótima conservação.',
                'location' => 'São Paulo',
            ],
            [
                'make' => 'Volkswagen',
                'model' => 'Jetta',
                'year' => 2020,
                'color' => 'Branco',
                'vin' => '3VWD17AJ2EM245678',
                'license_plate' => 'ABC5678',
                'mileage' => 30000,
                'engine' => '2.0L',
                'fuel_type' => 'Flex',
                'transmission' => 'Automático',
                'number_of_doors' => 4,
                'body_type' => 'Sedan',
                'drivetrain' => '4x2',
                'features' => 'Ar-condicionado, Central Multimídia, Direção Elétrica',
                'price' => 90000.00,
                'purchase_date' => '2023-08-15',
                'purchase_price' => 85000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 1,
                'description' => 'Veículo com baixa quilometragem, excelente estado.',
                'location' => 'Rio de Janeiro',
            ],
            [
                'make' => 'Ford',
                'model' => 'Ka',
                'year' => 2019,
                'color' => 'Vermelho',
                'vin' => '3FA6P0HD9HR123456',
                'license_plate' => 'LMN9012',
                'mileage' => 45000,
                'engine' => '1.0L',
                'fuel_type' => 'Flex',
                'transmission' => 'Manual',
                'number_of_doors' => 4,
                'body_type' => 'Hatch',
                'drivetrain' => '4x2',
                'features' => 'Ar-condicionado, Direção Hidráulica',
                'price' => 45000.00,
                'purchase_date' => '2023-05-01',
                'purchase_price' => 40000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 1,
                'description' => 'Econômico e ideal para uso urbano.',
                'location' => 'Curitiba',
            ],
            [
                'make' => 'Renault',
                'model' => 'Kwid',
                'year' => 2021,
                'color' => 'Prata',
                'vin' => '93HKF4K76MJ123456',
                'license_plate' => 'QRS5678',
                'mileage' => 20000,
                'engine' => '1.0L',
                'fuel_type' => 'Gasolina',
                'transmission' => 'Manual',
                'number_of_doors' => 4,
                'body_type' => 'Hatch',
                'drivetrain' => '4x2',
                'features' => 'Ar-condicionado, Direção Elétrica, Freios ABS',
                'price' => 52000.00,
                'purchase_date' => '2023-03-15',
                'purchase_price' => 48000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 0,
                'description' => 'Compacto, ideal para cidade.',
                'location' => 'Belo Horizonte',
            ],
            [
                'make' => 'Peugeot',
                'model' => '208',
                'year' => 2020,
                'color' => 'Azul',
                'vin' => 'VF3CRBFV1DY123456',
                'license_plate' => 'TUV2345',
                'mileage' => 38000,
                'engine' => '1.6L',
                'fuel_type' => 'Flex',
                'transmission' => 'Manual',
                'number_of_doors' => 4,
                'body_type' => 'Hatch',
                'drivetrain' => '4x2',
                'features' => 'Ar-condicionado, Direção Elétrica, Central Multimídia',
                'price' => 60000.00,
                'purchase_date' => '2023-01-25',
                'purchase_price' => 57000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 1,
                'description' => 'Veículo moderno e econômico.',
                'location' => 'Salvador',
            ],
            [
                'make' => 'Honda',
                'model' => 'Fit',
                'year' => 2018,
                'color' => 'Cinza',
                'vin' => '3HGGK5G53GM123456',
                'license_plate' => 'WXZ6789',
                'mileage' => 67000,
                'engine' => '1.5L',
                'fuel_type' => 'Gasolina',
                'transmission' => 'Automático',
                'number_of_doors' => 4,
                'body_type' => 'Hatch',
                'drivetrain' => '4x2',
                'features' => 'Ar-condicionado, Direção Hidráulica, Freios ABS',
                'price' => 75000.00,
                'purchase_date' => '2023-02-28',
                'purchase_price' => 72000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 1,
                'description' => 'Espaçoso e confortável, perfeito para família.',
                'location' => 'Recife',
            ],
            [
                'make' => 'Hyundai',
                'model' => 'Creta',
                'year' => 2019,
                'color' => 'Marrom',
                'vin' => 'KMHTD82EMS123456',
                'license_plate' => 'DEF2345',
                'mileage' => 50000,
                'engine' => '2.0L',
                'fuel_type' => 'Álcool',
                'transmission' => 'Automático',
                'number_of_doors' => 4,
                'body_type' => 'SUV',
                'drivetrain' => '4x2',
                'features' => 'Ar-condicionado, Freios ABS, Central Multimídia',
                'price' => 115000.00,
                'purchase_date' => '2023-04-10',
                'purchase_price' => 110000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 1,
                'description' => 'SUV com amplo espaço e moderno.',
                'location' => 'Fortaleza',
            ],
            [
                'make' => 'Mitsubishi',
                'model' => 'ASX',
                'year' => 2017,
                'color' => 'Prata',
                'vin' => 'JA4AP4AU3HU123456',
                'license_plate' => 'GHI7890',
                'mileage' => 65000,
                'engine' => '2.0L',
                'fuel_type' => 'Diesel',
                'transmission' => 'Automático',
                'number_of_doors' => 4,
                'body_type' => 'SUV',
                'drivetrain' => '4x4',
                'features' => 'Ar-condicionado, Teto Solar, Freios ABS, Airbags',
                'price' => 130000.00,
                'purchase_date' => '2023-05-10',
                'purchase_price' => 125000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 2,
                'description' => 'SUV robusto com excelente capacidade off-road.',
                'location' => 'Porto Alegre',
            ],
            [
                'make' => 'Toyota',
                'model' => 'RAV4',
                'year' => 2019,
                'color' => 'Branco',
                'vin' => 'JTMWFREV6JJ123456',
                'license_plate' => 'JKL3455',
                'mileage' => 40000,
                'engine' => '2.5L',
                'fuel_type' => 'Flex',
                'transmission' => 'Automático',
                'number_of_doors' => 4,
                'body_type' => 'SUV',
                'drivetrain' => '4x4',
                'features' => 'Ar-condicionado, Freios ABS, Direção Elétrica',
                'price' => 180000.00,
                'purchase_date' => '2023-06-15',
                'purchase_price' => 170000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 1,
                'description' => 'SUV espaçoso e econômico com tração integral.',
                'location' => 'São Paulo',
            ],
            [
                'make' => 'Fiat',
                'model' => 'Toro',
                'year' => 2021,
                'color' => 'Cinza',
                'vin' => '93C6RFJ34LM123456',
                'license_plate' => 'MNO5678',
                'mileage' => 30000,
                'engine' => '2.4L',
                'fuel_type' => 'Diesel',
                'transmission' => 'Automático',
                'number_of_doors' => 4,
                'body_type' => 'Pick-up',
                'drivetrain' => '4x4',
                'features' => 'Ar-condicionado, Direção Elétrica, Freios ABS',
                'price' => 140000.00,
                'purchase_date' => '2023-07-20',
                'purchase_price' => 135000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 1,
                'description' => 'Pick-up com ótimo desempenho e espaço para carga.',
                'location' => 'Curitiba',
            ],
            [
                'make' => 'Nissan',
                'model' => 'Versa',
                'year' => 2020,
                'color' => 'Prata',
                'vin' => '3N1CN7AP3KL123456',
                'license_plate' => 'OPQ2345',
                'mileage' => 35000,
                'engine' => '1.6L',
                'fuel_type' => 'Flex',
                'transmission' => 'Automático',
                'number_of_doors' => 4,
                'body_type' => 'Sedan',
                'drivetrain' => '4x2',
                'features' => 'Ar-condicionado, Direção Hidráulica, Airbags',
                'price' => 65000.00,
                'purchase_date' => '2023-08-30',
                'purchase_price' => 60000.00,
                'sale_date' => null,
                'sale_price' => null,
                'status' => 'Disponível',
                'previous_owners' => 1,
                'description' => 'Sedan econômico e confortável para o dia a dia.',
                'location' => 'Rio de Janeiro',
            ],
        ];

        foreach ($cars as $car) {
            Car::create($car);
        }
    }
}
